---
consul_template_platform: '{{ consul_template_os }}_{{ consul_template_arch }}'
consul_template_name: consul-template_{{ consul_template_ver }}_{{ consul_template_platform }}
consul_template_zip: '{{ consul_template_name }}.zip'
consul_template_tmp_zip: /tmp/{{ consul_template_zip }}
consul_template_zip_url: '{{ consul_template_mirror }}/{{ consul_template_ver }}/{{ consul_template_zip }}'
consul_template_install_dir: '{{ consul_template_install_bin_dir }}/{{ consul_template_name }}'
consul_template_checksum: '{{ consul_template_checksums[consul_template_ver][consul_template_platform] }}'
consul_template_exe: '{{ consul_template_install_dir }}/consul-template'
consul_template_link: '{{ consul_template_install_bin_dir }}/consul-template'
